baseURL: "https://kaushik-kumar-trs.github.io"
languageCode: "en-us"
title: "Kaushik"
theme: master
  
Paginate: 3
disqusShortname: gurusabarish
googleAnalytics: G-DWJJVE27WD
canonifyURLs:  true
  
markup:
  goldmark:
    renderer:
      unsafe: true

#Menus:
  #main:
    #- identifier: blog
      #name: Blog
      #title: Blog posts
      #url: /blogs
      #weight: 1

    #Dropdown menu
    #- identifier: dropdown
      #title: Example dropdown menu
      #name: Dropdown
      #weight: 2
    #- identifier: dropdown1
      #title: example dropdown 1
      #name: example 1
      #url: /#
      #parent: dropdown
      #weight: 1
    #- identifier: dropdown2
      #title: example dropdown 2
      #name: example 2
      #url: /#
      #parent: dropdown
      #weight: 2

params:
  #title: "Hugo Profile"
  #description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  #favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light" # dark
    color:  
        secondaryBackgroundColor: "Blue"
  
  navbar:
      position: absolute

  hero:
    enable: true
    intro: "Hi there! I'm "
    title: "Kaushik Kumar"
    #subtitle: 
    content: "A passionate and results-driven data enthusiast armed with a Master's in Computer Science and 4 years of rockstar experience in data engineering and analytics.
              
            From architecting data pipelines to orchestrating machine learning applications, I specialize in transforming raw numbers into valuable assets. Eager to bring this expertise into a dynamic role, infusing the power of data science and engineering to drive business growth starting January 2024.
              \n
              Let's make data waves together! 🚀✨"
    image: "/images/kk2.jpg"
    button:
      background - color: 
      enable: true  
      name: "Resume"
      url: "https://drive.google.com/file/d/1uW--_yd5WZB6y2sKjUzvgaeqml6YBdCx/view?usp=sharing"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/trs-kaushik
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/kaushikkumartrs/
        - icon: fab fa-instagram
          url: https://www.instagram.com/accounts/login/?next=/trs_kaushik/

  about:
    enable: true
    title: "I'm Open to work from January 2024"
    image: "/images/kk.jpg"
    content: |-
     As a seasoned analytics and data engieer, I've mastered the art of designing enterprise-level data warehousing pipelines on AWS, managing dream teams, and crafting the intricate techniques of machine learning & natural language processing, and creating dashboards that tell compelling stories.
     Certified as an AWS Solutions Architect and Tableau Desktop Specialist, I bring a comprehensive skill set to the table. This unique blend of skills, combined with a passion for turning data into actionable insights, positions me as a versatile professional ready to contribute to the dynamic field of data analytics.
     
    skills:
      enable: true
      title:
      items:
        - "AWS, Python, SQL, R, Spark, Data Modeling, ETL, Machine Learning, NLP, Data Visualization"
        - "Analytical, Strategic Planner, Team Player, Results Oriented, Tech-Savvy, Mentorship"
       

  # Experience
  experience:
    enable: true
    items:   
           
      - job: "Business Technology Associate Consultant"
        company: "ZS Associates"
        companyUrl: "https://zs.com"
        date: "June 2020 - Aug 2022"
        info:
          enable: true
          content: "Location: India, Pune "
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          India, Pune
            - Partnered with US-based fortune-500 life science companies to implement an enterprise-level data warehouse and analytics infrastructure on the AWS big data platform
            - Managed cross-functional teams with 6 associates to build ETL pipelines to process healthcare workflows
            - Outlined agile sprint requirements, and provided stakeholders with reporting data and dashboards
            - Performed ad-hoc analysis, and shared weekly reports and deliverables with stakeholders and managers
            - Designed 200+ reporting/analytical layers, optimized data flow, and storage across the Redshift clusters
            - Automated data transformations using dbt, integrating ~20 TB of data into AWS Redshift and Aurora
            - Performed data modeling, source-to-target mapping, data quality checks for seamless data integration
            - Provisioned AWS services, designed a seamless process to migrate on-premises applications into AWS
            - Developed analytical dashboards that boosted business by 18% and reduced clinical activity time by 27%
            - Performed EDA on the US census data and presented the findings in an insightful Tableau dashboard
            - Modeled a bagging regressor with 82% accuracy to predict the revenue potential of new clinical centers
            - Conducted sentiment analysis on social media reviews, driving performance insights for plasma centers
            - Conducted proof of concepts to process HCP-signed attestations using AWS Textract, Lambda, and SNS
            - Tech Stack: AWS, Python, SQL, R, Shiny, Spark, dbt, Machine Learning, Hive, Tableau, Excel

      - job: "Software Engineer - Data"
        company: "Infoview Technologies"
        companyUrl: "https://ivtlinfoview.com/"
        date: "June 2018 - September 2019"
        info:
          enable: true
          content: "Location: Chennai, India"
        featuredLink:
          enable: false
          url: "https://ivtlinfoview.com/"
        info:
          content: 
        content: |-
          Chennai, India
            - Streamlined the end-to-end backend development lifecycle for web applications tailored to fit the
            Japanese supply chain needs, to emphasize integrated DevOps and Agile principles
            - Developed 14 front-end supply chain modules and their corresponding back-end data flow architectures
            - Orchestrated Jenkins CI/CD pipelines integrated with SonarQube, ensuring efficient code deployment
            - Managed the development of PL/SQL stored procedures and triggers to streamline database operations
            - Designed 40% of the backend data model architecture with optimal normalization and indexing techniques
            - Developed an automated framework to mitigate manual data validations using advanced Excel by 100%
            - Tech Stack: AWS, Python, SQL, Java, Spring Boot, MongoDB, Rest API, GitLab, Jenkins, Docker, Excel
          
      - job: "Teaching Assitant - Data Models and Query Languages"
        company: "University at Buffalo"
        companyUrl: "https://engineering.buffalo.edu/"
        date: "January 2020 - Present"
        info:
          enable: true
          content: "Location: Buffalo, NY"
        featuredLink:
          enable: false
          url: "https://engineering.buffalo.edu/"
        info:
          content:
        content: |-
          Buffalo, NY
            - Led weekly doubt-solving sessions, instructing over 500 students during two semesters in Python, SQL, and the principles of constructing efficient data models and database architecture in line with industry standards
            - Developed quiz and exam questions, in addition to grading assessments and providing constructive feedback
            - Collaborated with professors in organizing workshops and actively participated in diverse research initiatives 
        

  education:
    enable: true
    items:
      - title: "Masters in Computer Science (Data Science and Artificial Intelligence)"
        school:
          name: "University at Buffalo, New York"
          url: "https://www.buffalo.edu"
        date: "2022 - 2024"
        GPA: "3.9 out of 4.0"
        content: |-
            - Teaching Assistant for Data Models and Query Languages at the School of Engineering, University at Buffalo
            - Computing Coursework:
                -  Analysis of Algorithms, Data Models and Query Languages, Distributed Systems, and Computer Security
            - Data Science Coursework: 
                - Machine Learning, Reinforcement Learning, Natural Language Processing, and Data Visualization

            Extracurricular Activities
             - Showcased "A Deep Reinforcement Learning for Complex Control Problems using OpenAI" at the semesterly UB project presentations
             - Conducted workshop on "Best Data Modeling and Data Warehousing Practices"
             
      - title: "Bachelor of Engineering in Computer Science and Engineering"
        school:
          name: "PSG Institute of Technology and Applied Research, India"
          url: "http://www.psgitech.ac.in/"
        date: "2014 - 2018"
        GPA: "8.2 out of 10.0"
        content: |- 
          - Graduated with an excellency award for securing a distinction level GPA of 8.2/10.0 
          - Computing Coursework: 
            - Operating Systems, Distributed Systems, Analysis of Alogrithms, Computer Architecture, Cryptography and Computer Networks
          - Data Science Coursework: 
            - Artificial Intelligence, Data Warehousing and  Data Mining, Big Data Analytics, Predictive Analytics, Database Management Systems 


          Extracurricular Activities
            - Participated in Smart India Hackathon, Presented a blood donation andriod application that showcases the donors and receivers in a geographical map
            - Served as the key member for conducting the university Annual Fest "YUKTHAHA"
            - Won multiple athletic competitions during all 4 years in the Intrumural tournements



  achievements:
    enable: true
    items:

      - title: AWS Certified Solutions Architect (Associate) - 2023
        content: "Gained proficiency in designing scalable and resilient cloud solutions, emphasizing the creation of analytical products. Skilled across various AWS services, specializing in developing optimized and secure architectures for reliability and performance. Additionally, acquired expertise in seamlessly integrating data analytics to ensure solutions scale efficiently, empowering organizations with robust analytical capabilities"
        url: "https://www.credly.com/badges/6a80a2d1-a51a-4363-a24f-771c52c9d2f7"
        image:  /images/projects/Colorization3.png
        
      - title: Tableau Certified Desktop Specialist - 2023
        content: Mastered the intricacies of crafting compelling data visualizations and analyses. Proficient in utilizing Tableau's powerful features, I create visually impactful dashboards that distill complex data into actionable insights. My expertise ensures effective communication of information and supports informed decision-making through concise and visually engaging solutions
        url: "https://www.credly.com/badges/22f0414f-a9ad-4c55-935c-b62dc92dc9a4"
        image: /images/projects/doge4.jpeg



  projects:
    enable: true
    items:
      - title: Clickbait Spoiler Generation using Large Language Models
        content: A NLP based application trained using advanced LLM's such as BERT, Mono-T5, and Zero-Shot learning to generate compelling spoilers for clickbaits
        image: /images/projects/CB.png
        featured:
          name: Click here to know more!
          link: https://github.com/trs-kaushik/NLP-Team-Synapse-Clickbait-Spoiler-Generation
        badges:
          - "NLP"
          - "PyTorch"
          - "Hugging Face"
          - "LLM Transformers"
          - "Sentiment Analysis"
          
        links:
          - icon: fab fa-github
            url: https://github.com/trs-kaushik/NLP-Team-Synapse-Clickbait-Spoiler-Generation


      - title: Deep Reinforcement Learning for Complex Control Problems
        content: Series of RL algorithms to solve challenging perception control problems in Open AI Gym environments such as Atari, Lunar Lander, and CartPole
        image: /images/projects/LLRL.png
        featured:
          name: Click here to know more!
          link: https://github.com/trs-kaushik/Reinforcement-Learning
        badges:
          - "Open AI Gym"
          - "PyTorch"
          - "Python"

        links:
          - icon: fab fa-github
            url: https://github.com/trs-kaushik/Reinforcement-Learning

      - title: YouTube Data Analysis using AWS
        content: A Streamlined AWS data pipeline, integrating Glue for ETL, Lambda for processing, Athena and Redshift for analysis, and QuickSight for building dynamic dashboard
        image: /images/projects/YTDA.png
        featured:
          name: Click here to know more!
          link: https://github.com/trs-kaushik/YouTube-Data-Analytics-Pipeline-with-AWS
        badges:
          - "AWS"
          - "Python"
          - "SQL"
          
        links:
          - icon: fab fa-github
            url: https://github.com/trs-kaushik/YouTube-Data-Analytics-Pipeline-with-AWS
            
            
      - title: Bitcoin Price Prediction using Sentiment Analysis
        content: A deep learning based application trained using LSTM networks, and Sentiment Analysis on top of historical Bitcoin prices, and Twitter tweets
        image: /images/projects/BTC.png
        featured:
          name: Click here to know more!
          link: https://github.com/trs-kaushik/Machine-learning/tree/master/Bitcoin%20Price%20Prediction%20-%20A%20Time%20Series%20Analysis
        badges:
          - "Time Series Analysis"
          - "Python"
          - "Pandas"
          - "Keras"
          - "Deep Learning"
          
        links:
          - icon: fab fa-github
            url: https://github.com/trs-kaushik/Machine-learning/tree/master/Bitcoin%20Price%20Prediction%20-%20A%20Time%20Series%20Analysis


      - title: Customer Purchaing Intension Recognition
        content: Leveraged statistical machine learning techniques such as Decision Trees, XGBoost, and Random Forest Classifiers to identify a potential customer 
        image: /images/projects/advert1.png
        featured:
          name: Click here to know more!
          link: https://github.com/trs-kaushik/Machine-learning/tree/master/Online_Shoppers_Intention
        badges:
          - "Python"
          - "SQL"
          - "Pandas"
          - "Flask"
          - "Scikit-learn"
          - "Machine Learning"
          
          
          
        links:
          - icon: fab fa-github
            url: https://github.com/trs-kaushik/Machine-learning/tree/master/Online_Shoppers_Intention


  contact:
    enable: true
    content: Shoot me a message whenever. Questions, greetings, or just a cyber rendezvous – I'm tuned in!
    email: kthogulu@buffalo.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/trs-kaushik
      linkedin: https://www.linkedin.com/in/kaushikkumartrs/
      instagram: https://www.instagram.com/trs_kaushik/
